### ISSUE TITLE
Missing Decoder Architectures Related to Resnet18

### ISSUE THREAD

**Issue by shahaamirbader** [dbraun-ub/NQGN#3]
Sorry to keep asking questions. I just noticed that options.py has multiple architectures listed for --decoder_arch. The default architecture listed is QGN_resnet18 which is different from the decoder architecture in networks folder. Can you share the other decoder architectures related to resnet18, that are listed in the options.py file?

**Comment by dbraun-ub** [comment]
The other architectures are just things I tried and forgot to remove them from the options.py file. The results from the paper are obtained with the available decoder. If you want more achitectures, you can have a look at https://github.com/kashyap7x/QGN.

**Comment by shahaamirbader** [comment]
Could you still share those architecture codes that you tried with Resnet18 encoder? I am more interested in the approach towards building decoders. You can share them via email at shahaamirbader@gmail.com. Any help would be appreciated.

**Comment by dbraun-ub** [comment]
Some of these architecture are still under development. I'll keep you in touch when it will be published. Probably in a few weeks.

**Comment by shahaamirbader** [comment]
I have a question though. I dont see skip connections in decoder being used. Is there a specific reason for that? Or is it a limitation with the resnet18 architecture?

**Comment by dbraun-ub** [comment]
There is skip connections in the decoder. The variable use_skip=True by default. You need to set it to false if you don't want to use it.

**Comment by shahaamirbader** [comment]
Thanks
